version:  '2.1'

services:
  mongo1:
    image: mongo
    container_name: mongo1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    ports:
      - 30001:30001
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"mongo1:30001\"},{_id:1,host:\"mongo2:30002\"},{_id:2,host:\"mongo3:30003\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s
  mongo2:
    image: mongo
    container_name: mongo2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    ports:
      - 30002:30002
  mongo3:
    image: mongo
    container_name: mongo3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    ports:
      - 30003:30003
  censor-daemon:
    image: censor-daemon
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    build: ./censor-daemon/
    ports: 
      - 9003:9003
    environment:
      PORT: 9003
      JSON_BODY_MAX_SIZE: "30mb"
      IS_PRODUCTION: "false"
      MAX_PAGE_SIZE: 50
      LISTS_SERVICE_URL: "http://whitelist-api:9002/api/lists/graylist"
      FIXED_ALLOWED_WORDS: "calender-name,calender,day-1,desctiption,content"
      FIXED_ALLOWED_CHARS: "{,},:,\",.,[,]"
      REPLACE_STRING: "*"
      MIN_SPACE_BETWEEN_PREFIX_AND_SUFFIX: 1
      PREFIX_ALLOWED_LETTERS_COUNT: 1
      SUFFIX_ALLOWED_LETTERS_COUNT: 0
      STORAGE_TYPE: "mongo"
      MONGO_URI: "mongodb://mongo1:30001,mongo2:30002,mongo3:30003/my-replica-set"
      MONGO_DATABASE: "development"
  whitelist-api:
    image: whitelist-api
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    build: ./whitelist-api/
    ports: 
      - 9002:9002
    environment:
      PORT: 9002
      JSON_BODY_MAX_SIZE: "30mb"
      IS_PRODUCTION: "false"
      MAX_PAGE_SIZE: 50
      STORAGE_TYPE: "mongo"
      ALLOWED_USERS: "user1@example.com"
      FRONTEND_URL: "whitelist-ui:80"
      MONGO_URI: "mongodb://mongo1:30001,mongo2:30002,mongo3:30003/my-replica-set"
      MONGO_DATABASE: "development"
      SAML_ENTRY_POINT: "http://localhost:8080/simplesaml/saml2/idp/SSOService.php"
      SAML_ISSUER: "http://localhost:9002/metadata.xml"
      SAML_CALLBACK_URL: "http://localhost:9002/auth/saml/callback"
      METADATA_ENTITY_ID: "http://localhost:9002/metadata.xml"
      PROFILE_EXTRACTOR_ID: "email"
  whitelist-ui:
    image: whitelist-ui
    build: ./whitelist-ui/
    stdin_open: true
    ports: 
      - 80:80
  testsamlidp_idp:
    image: kristophjunge/test-saml-idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: "http://localhost:9002/metadata.xml"
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: "http://localhost:9002/auth/saml/callback"
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: "http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp"
      SAML_ISSUER: "http://localhost:9002/metadata.xml"
      SAML_CALLBACK_URL: "http://localhost:9002/auth/saml/callback"
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8080:8080"